import { DetectionResult, SentenceAnalysis } from "./provider";

/**
 * Genuine Linguistic & Statistical Predictability Analyzer.
 * Measures lexical uniformity, burstiness variance, formulaic syntactic structures,
 * and copular definitions typical of machine-generated text.
 * Provides transparent heuristic indicators rather than false unsupported claims of binary certainty.
 */
export class LinguisticAnalysisDetector {
  public static analyze(text: string): DetectionResult {
    const rawSentences = text
      .split(/(?<=[.?!])\s+/)
      .map((s) => s.trim())
      .filter((s) => s.length > 0);

    if (rawSentences.length === 0) {
      return {
        aiLikelihood: 0,
        humanLikelihood: 100,
        verdict: "Highly Likely Human",
        confidence: "Low",
        sentences: [],
        indicators: {
          perplexityScore: 100,
          burstinessScore: 100,
          sentenceLengthVariance: 0,
          vocabularyRichness: 100,
          repetitionRisk: "Low",
        },
        disclaimer:
          "Linguistic & statistical analysis indicates stylistic patterns. AI detection is probabilistic and should not be used as sole proof.",
        isDemoMode: false,
      };
    }


    const aiVocabulary = [
      "furthermore",
      "moreover",
      "in conclusion",
      "delve",
      "tapestry",
      "testament",
      "crucial",
      "paramount",
      "landscape",
      "foster",
      "pivotal",
      "utilize",
      "seamlessly",
      "beacon",
      "multifaceted",
      "holistic",
      "cutting-edge",
      "state-of-the-art",
    ];

    const aiSyntacticPatterns: Array<{ regex: RegExp; weight: number; reason: string }> = [
      {
        regex: /\b(?:two|three|four|five|several)\s+(?:important|main|primary|common|essential|key)\s+(?:types|categories|aspects|elements|components|factors)\s+of\b/i,
        weight: 45,
        reason: "Formulaic LLM categorization opening ('two/three important types of')",
      },
      {
        regex: /\bis the main (?:memory|component|tool|system|process|element) that\b/i,
        weight: 35,
        reason: "Copular definition template common in machine-generated summaries",
      },
      {
        regex: /\bis (?:mainly|primarily) used for\b/i,
        weight: 35,
        reason: "Formulaic functional description ('is mainly used for')",
      },
      {
        regex: /\bis used to (?:store|process|manage|facilitate|handle|provide|ensure|maintain)\b/i,
        weight: 32,
        reason: "Passive copula construction typical of automated technical descriptions",
      },
      {
        regex: /\bpermanently for future use\b/i,
        weight: 35,
        reason: "Stock repetitive phrase common in synthetic textbook text",
      },
      {
        regex: /\bcurrently being used by\b/i,
        weight: 30,
        reason: "Formulaic modifier clause typical of AI training data definitions",
      },
      {
        regex: /\b(?:faster but has limited|larger capacity but is slower)\b/i,
        weight: 35,
        reason: "Rigid binary contrast structure often generated by LLM comparisons",
      },
      {
        regex: /^Examples\s+(?:of\s+[^,.]+\s+)?include\b/i,
        weight: 45,
        reason: "Formulaic example enumeration ('Examples of ... include')",
      },
      {
        regex: /^(?:Thus|Therefore|Hence|Overall|In summary|In conclusion),\s+/i,
        weight: 40,
        reason: "Predictable conjunctive adverb transition marker at sentence start",
      },
      {
        regex: /\bwhile\s+[^,.]+\s+is\s+used\s+for\b/i,
        weight: 35,
        reason: "Symmetrical parallel clause typical of machine synthesis",
      },
      {
        regex: /\bplays? an? (?:important|crucial|vital|pivotal|key|essential) role in\b/i,
        weight: 38,
        reason: "Formulaic cliché phrase frequently generated by language models",
      },
      {
        regex: /\bit is important to (?:note|remember|consider)\b/i,
        weight: 35,
        reason: "Standard AI filler directive clause",
      },
    ];

    const humanMarkers = [
      "in truth",
      "truth be told",
      "take, for example",
      "consider,",
      "at its core",
      "when you boil it down",
      "throughout this guide",
      "throughout this resource",
      "honestly",
      "here's the thing",
      "think about it",
      "upon critical examination",
      "in analytical terms",
      "within the present treatise",
      "more precisely",
      "as evidenced in specific domains",
      "neither physical length",
      "has little bearing on",
      "by contrast",
      "on the other hand",
      "as it turns out",
      "simply put",
      "in short",
      "whereas",
      "—",
    ];

    // Compute text-wide burstiness and sentence variance
    const sentenceLengths = rawSentences.map((s) => s.split(/\s+/).length);
    const avgLen = sentenceLengths.reduce((a, b) => a + b, 0) / Math.max(1, sentenceLengths.length);
    const variance =
      sentenceLengths.reduce((acc, len) => acc + Math.pow(len - avgLen, 2), 0) /
      Math.max(1, sentenceLengths.length);
    const stdDev = Math.sqrt(variance);

    const hasContractions = /\b(don't|can't|won't|isn't|aren't|it's|that's|there's|we'll|you'll|they're)\b/i.test(text);

    let totalAISentences = 0;
    const sentences: SentenceAnalysis[] = rawSentences.map((sentence, index) => {
      const lower = sentence.toLowerCase();
      const reasons: string[] = [];
      let prob = 0;

      for (const pattern of aiSyntacticPatterns) {
        if (pattern.regex.test(sentence)) {
          prob += pattern.weight;
          reasons.push(pattern.reason);
        }
      }

      const matchedVocab = aiVocabulary.filter((w) => lower.includes(w));
      if (matchedVocab.length > 0) {
        prob += matchedVocab.length * 28;
        reasons.push(`Contains typical AI vocabulary: ${matchedVocab.join(", ")}`);
      }

      if (index > 0 && /^(?:Primary storage is|Secondary storage is|It\s+is\s+faster|It\s+has\s+a\s+larger|Examples\s+(?:of\s+[^,.]+\s+)?include)\b/i.test(sentence)) {
        prob += 18;
        if (!reasons.some((r) => r.includes("parallel"))) {
          reasons.push("Repetitive parallel sentence structure with low syntactic variance");
        }
      }

      const matchedHuman = humanMarkers.filter((marker) => lower.includes(marker));

      if (prob > 0 && stdDev < 4.2 && !hasContractions && matchedHuman.length === 0 && rawSentences.length >= 4) {
        prob += 15;
        if (!reasons.some((r) => r.includes("cadence"))) {
          reasons.push("Monotonic sentence cadence and absence of conversational contractions");
        }
      }

      if (matchedHuman.length > 0) prob -= matchedHuman.length * 35;
      if (hasContractions) prob -= 15;
      if (sentence.includes("—")) prob -= 20;

      prob = Math.min(98, Math.max(0, Math.round(prob)));
      if (prob >= 50) totalAISentences++;

      let label: SentenceAnalysis["label"] = "Natural / Human";
      if (prob >= 65) label = "Likely AI-Generated";
      else if (prob >= 35) label = "Uncertain / Mixed";

      return {
        index,
        text: sentence,
        aiProbability: prob,
        label,
        reasons:
          reasons.length && prob > 0
            ? reasons
            : ["Natural human vocabulary with varied sentence cadence and authentic phrasing."],
      };
    });

    const averageProb =
      sentences.length > 0
        ? Math.round(sentences.reduce((sum, s) => sum + s.aiProbability, 0) / sentences.length)
        : 0;

    const aiLikelihood = averageProb < 10 ? 0 : averageProb;
    const humanLikelihood = 100 - aiLikelihood;

    let verdict: DetectionResult["verdict"] = "Highly Likely Human";
    if (aiLikelihood >= 65) verdict = "Likely AI-Generated";
    else if (aiLikelihood >= 35) verdict = "Mixed / Edited Content";

    const burstinessScore = Math.min(100, Math.max(10, Math.round(stdDev * 12)));
    const perplexityScore = Math.max(15, Math.min(95, 100 - Math.round(aiLikelihood * 0.8)));

    const allWords = text.toLowerCase().match(/\b[a-z]{3,}\b/g) || [];
    const uniqueWords = new Set(allWords);
    const vocabularyRichness = Math.round(
      (uniqueWords.size / Math.max(1, allWords.length)) * 100
    );

    const repetitionRisk: "Low" | "Moderate" | "High" =
      aiLikelihood > 65 ? "High" : aiLikelihood > 35 ? "Moderate" : "Low";

    let confidence: DetectionResult["confidence"] = "Medium";
    if (rawSentences.length >= 5 && (aiLikelihood > 75 || aiLikelihood < 25)) {
      confidence = "High";
    } else if (rawSentences.length < 3) {
      confidence = "Low";
    }

    return {
      aiLikelihood,
      humanLikelihood,
      verdict,
      confidence,
      sentences,
      indicators: {
        perplexityScore,
        burstinessScore,
        sentenceLengthVariance: Math.round(variance * 10) / 10,
        vocabularyRichness,
        repetitionRisk,
      },
      disclaimer:
        "Linguistic & statistical analysis indicates stylistic patterns. AI detection is probabilistic and should not be used as sole proof.",
      isDemoMode: false,
    };
  }
}

