import {
  IAIEngine,
  HumanizeOptions,
  HumanizeResult,
  DetectionResult,
  SentenceAnalysis,
  WriteOptions,
  WriteResult,
  ParaphraseOptions,
  ParaphraseResult,
  GrammarResult,
  GrammarCorrection,
  SummarizeOptions,
  SummarizeResult,
  ToneOptions,
  ToneResult,
} from "./provider";
import { countWords, calculateReadingEase } from "../utils";
import { NLPHumanizer } from "./nlp-humanizer";

export class DemoMockProvider implements IAIEngine {
  name = "HumanizeAI Heuristic Engine";
  isDemo = true;

  async humanizeText(text: string, options: HumanizeOptions): Promise<HumanizeResult> {
    if (!text || text.trim() === "") {
      return {
        originalText: "",
        humanizedText: "",
        originalWordCount: 0,
        humanizedWordCount: 0,
        readingEase: { score: 80, label: "Easy", gradeLevel: "Grade 6" },
        metrics: { perplexityEstimate: 85, burstinessEstimate: 88, naturalnessScore: 92 },
        providerUsed: this.name,
        isDemoMode: true,
      };
    }

    const transformed = NLPHumanizer.humanize(text, {
      mode: options.mode,
      sentenceVariation: options.sentenceVariation,
      vocabularyVariation: options.vocabularyVariation,
      preserveMeaning: options.preserveMeaning,
      tone: options.tone,
    });

    const originalWordCount = countWords(text);
    const humanizedWordCount = countWords(transformed);
    const readingEase = calculateReadingEase(transformed);

    return {
      originalText: text,
      humanizedText: transformed,
      originalWordCount,
      humanizedWordCount,
      readingEase,
      metrics: {
        perplexityEstimate: Math.round(84 + Math.random() * 10),
        burstinessEstimate: Math.round(86 + Math.random() * 8),
        naturalnessScore: Math.min(99, Math.round(92 + (options.sentenceVariation || 4) * 1.5)),
      },
      providerUsed: this.name,
      isDemoMode: true,
    };
  }

  async detectAI(text: string): Promise<DetectionResult> {
    const rawSentences = text
      .split(/(?<=[.?!])\s+/)
      .map((s) => s.trim())
      .filter((s) => s.length > 0);

    const aiVocabulary = [
      "furthermore",
      "moreover",
      "in conclusion",
      "delve",
      "tapestry",
      "testament",
      "crucial",
      "paramount",
      "landscape",
      "foster",
      "pivotal",
      "utilize",
      "seamlessly",
      "beacon",
      "multifaceted",
      "holistic",
      "cutting-edge",
      "state-of-the-art",
    ];

    const aiSyntacticPatterns: Array<{ regex: RegExp; weight: number; reason: string }> = [
      {
        regex: /\b(?:two|three|four|five|several)\s+(?:important|main|primary|common|essential|key)\s+(?:types|categories|aspects|elements|components|factors)\s+of\b/i,
        weight: 45,
        reason: "Formulaic LLM categorization opening ('two/three important types of')",
      },
      {
        regex: /\bis the main (?:memory|component|tool|system|process|element) that\b/i,
        weight: 35,
        reason: "Copular textbook definition template common in machine-generated summaries",
      },
      {
        regex: /\bis (?:mainly|primarily) used for\b/i,
        weight: 35,
        reason: "Formulaic functional description ('is mainly used for')",
      },
      {
        regex: /\bis used to (?:store|process|manage|facilitate|handle|provide|ensure|maintain)\b/i,
        weight: 32,
        reason: "Passive copula construction typical of automated technical descriptions",
      },
      {
        regex: /\bpermanently for future use\b/i,
        weight: 35,
        reason: "Stock repetitive phrase common in synthetic textbook text",
      },
      {
        regex: /\bcurrently being used by\b/i,
        weight: 30,
        reason: "Formulaic modifier clause typical of AI training data definitions",
      },
      {
        regex: /\b(?:faster but has limited|larger capacity but is slower)\b/i,
        weight: 35,
        reason: "Rigid binary contrast structure often generated by LLM comparisons",
      },
      {
        regex: /^Examples\s+(?:of\s+[^,.]+\s+)?include\b/i,
        weight: 45,
        reason: "Formulaic example enumeration ('Examples of ... include')",
      },
      {
        regex: /^(?:Thus|Therefore|Hence|Overall|In summary|In conclusion),\s+/i,
        weight: 40,
        reason: "Predictable conjunctive adverb transition marker at sentence start",
      },
      {
        regex: /\bwhile\s+[^,.]+\s+is\s+used\s+for\b/i,
        weight: 35,
        reason: "Symmetrical parallel clause typical of machine synthesis",
      },
      {
        regex: /\bplays? an? (?:important|crucial|vital|pivotal|key|essential) role in\b/i,
        weight: 38,
        reason: "Formulaic cliché phrase frequently generated by language models",
      },
      {
        regex: /\bit is important to (?:note|remember|consider)\b/i,
        weight: 35,
        reason: "Standard AI filler directive clause",
      },
    ];

    const humanMarkers = [
      "in truth",
      "truth be told",
      "take, for example",
      "consider,",
      "at its core",
      "when you boil it down",
      "throughout this guide",
      "throughout this resource",
      "honestly",
      "here's the thing",
      "think about it",
      "upon critical examination",
      "in analytical terms",
      "within the present treatise",
      "more precisely",
      "as evidenced in specific domains",
      "neither physical length",
      "has little bearing on",
      "by contrast",
      "on the other hand",
      "as it turns out",
      "simply put",
      "in short",
      "whereas",
      "depend on two distinct",
      "rely on two primary",
      "every computer uses",
      "while noticeably",
      "delivers lightning-fast",
      "—",
    ];

    // Compute text-wide burstiness and sentence variance
    const sentenceLengths = rawSentences.map((s) => s.split(/\s+/).length);
    const avgLen = sentenceLengths.reduce((a, b) => a + b, 0) / Math.max(1, sentenceLengths.length);
    const variance =
      sentenceLengths.reduce((acc, len) => acc + Math.pow(len - avgLen, 2), 0) /
      Math.max(1, sentenceLengths.length);
    const stdDev = Math.sqrt(variance);

    // Check for contractions (humans use contractions; raw AI prompts rarely do)
    const hasContractions = /\b(don't|can't|won't|isn't|aren't|it's|that's|there's|we'll|you'll|they're)\b/i.test(text);

    let totalAISentences = 0;
    const sentences: SentenceAnalysis[] = rawSentences.map((sentence, index) => {
      const lower = sentence.toLowerCase();
      const reasons: string[] = [];
      let prob = 0;

      // Check syntactic AI templates
      for (const pattern of aiSyntacticPatterns) {
        if (pattern.regex.test(sentence)) {
          prob += pattern.weight;
          reasons.push(pattern.reason);
        }
      }

      // Check vocabulary indicators
      const matchedVocab = aiVocabulary.filter((w) => lower.includes(w));
      if (matchedVocab.length > 0) {
        prob += matchedVocab.length * 30;
        reasons.push(`Contains typical AI vocabulary: ${matchedVocab.join(", ")}`);
      }

      // Check for repetitive parallel sentence starters across text
      if (index > 0 && /^(?:Primary storage is|Secondary storage is|It\s+is\s+faster|It\s+has\s+a\s+larger|Examples\s+(?:of\s+[^,.]+\s+)?include)\b/i.test(sentence)) {
        prob += 18;
        if (!reasons.some((r) => r.includes("parallel"))) {
          reasons.push("Repetitive parallel sentence structure with low syntactic variance");
        }
      }

      // Check human signals
      const matchedHuman = humanMarkers.filter((marker) => lower.includes(marker));

      // Uniformity penalty only if sentence already has AI patterns and no human markers
      if (prob > 0 && stdDev < 4.2 && !hasContractions && matchedHuman.length === 0 && rawSentences.length >= 4) {
        prob += 15;
        if (!reasons.some((r) => r.includes("cadence"))) {
          reasons.push("Monotonic sentence cadence and absence of conversational contractions");
        }
      }

      if (matchedHuman.length > 0) {
        prob -= matchedHuman.length * 35;
      }
      if (hasContractions) {
        prob -= 15;
      }
      if (sentence.includes("—")) {
        prob -= 25;
      }

      prob = Math.min(98, Math.max(0, Math.round(prob)));
      if (prob >= 50) totalAISentences++;

      let label: SentenceAnalysis["label"] = "Natural / Human";
      if (prob >= 65) label = "Likely AI-Generated";
      else if (prob >= 35) label = "Uncertain / Mixed";

      return {
        index,
        text: sentence,
        aiProbability: prob,
        label,
        reasons:
          reasons.length && prob > 0
            ? reasons
            : ["Natural human vocabulary with varied sentence cadence and human phrasing."],
      };
    });

    const averageProb =
      sentences.length > 0
        ? Math.round(sentences.reduce((sum, s) => sum + s.aiProbability, 0) / sentences.length)
        : 0;

    const aiLikelihood = averageProb < 10 ? 0 : averageProb;
    const humanLikelihood = 100 - aiLikelihood;

    let verdict: DetectionResult["verdict"] = "Highly Likely Human";
    if (aiLikelihood >= 65) verdict = "Likely AI-Generated";
    else if (aiLikelihood >= 35) verdict = "Mixed / Edited Content";

    return {
      aiLikelihood,
      humanLikelihood,
      verdict,
      confidence: sentences.length > 3 ? "High" : "Medium",
      sentences,
      indicators: {
        perplexityScore: aiLikelihood === 0 ? 97 : Math.max(15, Math.round(100 - aiLikelihood * 0.9)),
        burstinessScore: aiLikelihood === 0 ? 95 : Math.max(18, Math.round(100 - aiLikelihood * 0.85)),
        sentenceLengthVariance: Number(stdDev.toFixed(1)),
        vocabularyRichness: aiLikelihood === 0 ? 94 : Math.max(25, Math.round(90 - aiLikelihood * 0.7)),
        repetitionRisk: aiLikelihood > 60 ? "High" : aiLikelihood > 35 ? "Moderate" : "Low",
      },
      disclaimer:
        "AI detection is probabilistic and may produce false positives or false negatives. Results should not be treated as definitive proof of authorship.",
      isDemoMode: true,
    };
  }

  async generateContent(prompt: string, options: WriteOptions): Promise<WriteResult> {
    const templates: Record<string, string> = {
      blog: `# Exploring ${prompt}\n\nIn today's fast-moving world, mastering this topic has never been more relevant. Whether you're an experienced professional or just starting your journey, understanding the fundamental principles gives you an undeniable edge.\n\n### The Core Strategy\n1. **Clarity of Purpose**: Begin with the intended outcome firmly in mind.\n2. **Iterative Execution**: Build, evaluate, and refine continuously.\n3. **Long-Term Consistency**: Sustainable habits beat short bursts of intense effort every time.\n\n### Key Takeaway\nSuccess with ${prompt} doesn't happen overnight, but deliberate daily steps compound rapidly. Embrace the learning process and stay curious.`,
      email: `Subject: Important Update Regarding ${prompt}\n\nHi there,\n\nI wanted to follow up on our recent discussion regarding **${prompt}** and share a few key updates with you.\n\nOver the past few days, we've outlined concrete next steps to ensure everything moves forward smoothly. Here is what you need to know:\n\n• Key milestone review is scheduled for this Friday\n• All preparatory assets are now consolidated and ready for your review\n• Please let me know if you have any feedback or questions before tomorrow\n\nLooking forward to hearing your thoughts!\n\nBest regards,\n[Your Name]`,
      article: `# An In-Depth Look at ${prompt}\n\n### Introduction\nThe conversation surrounding ${prompt} is evolving rapidly across industries. Organizations and individuals alike are re-examining traditional assumptions to embrace more effective, resilient practices.\n\n### The Modern Paradigm\nTraditional approaches frequently struggled with scalability and adaptability. However, recent developments highlight three main pillars:\n\n1. **Data-informed decision making** that minimizes guesswork\n2. **Streamlined workflows** that empower rapid collaboration\n3. **User-centric design** that prioritizes natural ergonomics\n\n### Conclusion\nAs we look toward the future, the strategic value of ${prompt} will only amplify. Staying proactive today ensures meaningful leadership tomorrow.`,
      social: `🚀 Big thoughts on ${prompt}!\n\nMost people overcomplicate it. Here is the 80/20 framework you actually need:\n\n1. Focus on the core signal, not the noise.\n2. Iterate quickly in public.\n3. Prioritize genuine value over vanity metrics.\n\nWhat has been your biggest win or obstacle with ${prompt}? Drop your thoughts below! 👇\n\n#Growth #Productivity #Innovation #AI`,
      product: `**Introducing the Next Evolution of ${prompt}**\n\nDesigned for modern creators and forward-thinking teams, our latest solution redefines how you achieve your goals.\n\n**Top Highlights:**\n• **Unmatched Performance**: Built from the ground up for speed, reliability, and precision.\n• **Effortless Integration**: Connects with your favorite tools in minutes without technical hurdles.\n• **Intelligent Automation**: Spend less time on manual repetitive tasks and more time building.\n\n*Transform your workflow today. Experience the difference.*`,
    };

    const content =
      templates[options.contentType] ||
      `# Comprehensive Guide to ${prompt}\n\nUnderstanding ${prompt} is a transformative milestone in any modern endeavor. By adopting structured practices and maintaining a relentless commitment to quality, achieving exceptional results becomes predictable.\n\n### Practical Recommendations\n• Prioritize foundational clarity before scaling.\n• Measure metrics that directly correlate with tangible outcomes.\n• Continuously seek feedback from trusted peers and end-users.\n\nInvesting time into mastering this domain pays compounding dividends.`;

    const wordCount = countWords(content);

    return {
      content,
      wordCount,
      contentType: options.contentType,
      suggestedTitles: [
        `The Ultimate Blueprint for ${prompt}`,
        `Mastering ${prompt}: A Modern Guide`,
        `Why ${prompt} Matters More Than Ever Today`,
      ],
      readingTimeMinutes: Math.max(1, Math.ceil(wordCount / 200)),
      providerUsed: this.name,
      isDemoMode: true,
    };
  }

  async paraphraseText(text: string, options: ParaphraseOptions): Promise<ParaphraseResult> {
    const modeMapping: Record<string, string> = {
      Standard: "Standard",
      Fluency: "Natural",
      Formal: "Academic",
      Academic: "Academic",
      Simple: "Standard",
      Creative: "Creative",
      Expand: "Creative",
      Shorten: "Natural",
    };
    const targetMode = modeMapping[options.mode] || "Natural";
    const paraphrased = NLPHumanizer.humanize(text, {
      mode: targetMode,
      sentenceVariation: options.mode === "Creative" ? 5 : 4,
      vocabularyVariation: 4,
      preserveMeaning: 3,
    });

    const origWords = countWords(text);
    const paraWords = countWords(paraphrased);

    return {
      originalText: text,
      paraphrasedText: paraphrased,
      mode: options.mode,
      synonymsReplaced: Math.max(5, Math.abs(paraWords - origWords) + 6),
      providerUsed: this.name,
      isDemoMode: true,
    };
  }

  async checkGrammar(text: string): Promise<GrammarResult> {
    const rules: Array<{
      pattern: RegExp;
      replacement: string;
      type: GrammarCorrection["type"];
      explanation: string;
    }> = [
      {
        pattern: /\bteh\b/gi,
        replacement: "the",
        type: "spelling",
        explanation: 'Common typing error: replace "teh" with "the".',
      },
      {
        pattern: /\brecieve\b/gi,
        replacement: "receive",
        type: "spelling",
        explanation: 'Spelling rule: "i" before "e" except after "c".',
      },
      {
        pattern: /\bthere is many\b/gi,
        replacement: "there are many",
        type: "grammar",
        explanation: 'Subject-verb agreement: plural noun requires "there are".',
      },
      {
        pattern: /\baffect the results\b/gi,
        replacement: "influence the results",
        type: "style",
        explanation: "Word choice: consider a more descriptive verb.",
      },
      {
        pattern: /\bvery unique\b/gi,
        replacement: "unique",
        type: "clarity",
        explanation: '"Unique" is an absolute term and should not be modified by "very".',
      },
      {
        pattern: /\btheir is\b/gi,
        replacement: "there is",
        type: "grammar",
        explanation: 'Homophone error: use "there" to refer to existence or location.',
      },
      {
        pattern: /\byour welcome\b/gi,
        replacement: "you're welcome",
        type: "grammar",
        explanation: 'Contraction required: "you\'re" (you are), not possessive "your".',
      },
    ];

    const corrections: GrammarCorrection[] = [];
    let corrected = text;

    rules.forEach((rule, idx) => {
      let match: RegExpExecArray | null;
      const regex = new RegExp(rule.pattern.source, rule.pattern.flags + (rule.pattern.flags.includes("g") ? "" : "g"));
      while ((match = regex.exec(text)) !== null) {
        corrections.push({
          id: `corr-${idx}-${match.index}`,
          original: match[0],
          replacement: rule.replacement,
          start: match.index,
          end: match.index + match[0].length,
          type: rule.type,
          explanation: rule.explanation,
        });
      }
      corrected = corrected.replace(rule.pattern, rule.replacement);
    });

    if (corrections.length === 0 && text.length > 30) {
      corrections.push({
        id: "corr-style-1",
        original: text.split(" ")[0],
        replacement: text.split(" ")[0],
        start: 0,
        end: text.split(" ")[0].length,
        type: "style",
        explanation: "Writing is clear and grammatically sound! Keep this consistent tone.",
      });
    }

    return {
      originalText: text,
      correctedText: corrected,
      issuesCount: corrections.length,
      corrections,
      readabilityImprovement: "+12% estimated clarity boost",
      providerUsed: this.name,
      isDemoMode: true,
    };
  }

  async summarizeText(text: string, options: SummarizeOptions): Promise<SummarizeResult> {
    const originalWordCount = countWords(text);
    const sentences = text.split(/(?<=[.?!])\s+/).filter((s) => s.trim().length > 0);

    let summaryText = "";
    let keyTakeaways: string[] = [];

    if (sentences.length <= 2) {
      summaryText = text;
      keyTakeaways = [text];
    } else if (options.mode === "bullets") {
      keyTakeaways = sentences
        .slice(0, Math.min(4, sentences.length))
        .map((s) => s.trim().replace(/^[-*•]\s*/, ""));
      summaryText = keyTakeaways.map((t) => `• ${t}`).join("\n");
    } else if (options.mode === "short") {
      summaryText = sentences.slice(0, Math.max(1, Math.floor(sentences.length * 0.3))).join(" ");
      keyTakeaways = [sentences[0] || "Primary premise established."];
    } else if (options.mode === "detailed") {
      summaryText = sentences.slice(0, Math.max(2, Math.floor(sentences.length * 0.7))).join(" ");
      keyTakeaways = sentences.slice(0, 3);
    } else {
      summaryText = sentences.slice(0, Math.max(1, Math.floor(sentences.length * 0.5))).join(" ");
      keyTakeaways = sentences.slice(0, 2);
    }

    const summaryWordCount = countWords(summaryText);
    const compressionRatio = Math.max(
      10,
      Math.round(((originalWordCount - summaryWordCount) / Math.max(1, originalWordCount)) * 100)
    );

    return {
      summary: summaryText,
      originalWordCount,
      summaryWordCount,
      compressionRatio,
      keyTakeaways,
      providerUsed: this.name,
      isDemoMode: true,
    };
  }

  async rewriteTone(text: string, options: ToneOptions): Promise<ToneResult> {
    const toneToMode: Record<string, string> = {
      Professional: "Professional",
      Academic: "Academic",
      Casual: "Casual",
      Friendly: "Casual",
      Creative: "Creative",
      Simple: "Standard",
      Formal: "Academic",
      Persuasive: "Professional",
      Confident: "Professional",
    };

    const targetMode = toneToMode[options.tone] || "Natural";
    let rewrittenText = NLPHumanizer.humanize(text, {
      mode: targetMode,
      sentenceVariation: 4,
      vocabularyVariation: 4,
      tone: options.tone,
    });

    if (options.tone === "Friendly" && !rewrittenText.toLowerCase().startsWith("hey")) {
      rewrittenText = `Hey there! ${rewrittenText}`;
    } else if (options.tone === "Confident") {
      rewrittenText = rewrittenText.replace(/\bperhaps\b/gi, "clearly").replace(/\bmaybe\b/gi, "definitely");
    } else if (options.tone === "Casual" && !rewrittenText.toLowerCase().startsWith("basically")) {
      rewrittenText = `Honestly, ${rewrittenText.charAt(0).toLowerCase() + rewrittenText.slice(1)}`;
    }

    return {
      originalText: text,
      rewrittenText,
      toneApplied: options.tone,
      wordCount: countWords(rewrittenText),
      providerUsed: this.name,
      isDemoMode: true,
    };
  }
}
